### ISSUE TITLE
No playlist generated

### ISSUE THREAD

**Issue by Enzemo** [jeremys18/BeatSaberPlaylistMover#3]
Ran the version 1.1 of the tool, pointed it at my Steam installation of Beat Saber 1.6, and clicked start.

The tool takes a long time to collect song hashes, and after this stage, very quickly outputs another line and closes the window. I do not get a chance to read what it says, but I think that it said it was generating playlists.

After the tool force closes no changes have been made to the beat saber directory and no playlists appear in game.

I have tried to run as administrator and am using a standard file structure, I. E all songs in Custom Levels and all playlists in Playlists

**Comment by Enzemo** [comment]
Managed to catch it this time, it says looking for playlists and then force closes. I have tried placing a folder called Playlists into both the Beat Saber/ directory and BeatSaber/Beat Saber_Data, and tried with both in place, but neither are recognised by the tool. They are in .bplist format, changing to .json does not resolve

**Comment by nissel** [comment]
I had the same issue and managed to solve it. Turns out the default folders.xml that songcore comes with has a couple of example folders in, but they have boolean WIP value of 'False' (with the capital letter). This crashes the XML parser as only 'true' or 'false' are allowed.

Simple fix edit your UserData\SongCore\folders.xml file by hand and remove the bad examples before running the tool.

**Comment by Enzemo** [comment]
This worked, thanks very much! I'll leave the issue until a fix can be done, sure its going to be as simple as something like Lower() 

Shame it doesn't allow songs to be in more than one playlist at a time, but nevermind

**Comment by nissel** [comment]
> This worked, thanks very much! I'll leave the issue until a fix can be done, sure its going to be as simple as something like Lower()
> 
> Shame it doesn't allow songs to be in more than one


> This worked, thanks very much! I'll leave the issue until a fix can be done, sure its going to be as simple as something like Lower()
> 
> Shame it doesn't allow songs to be in more than one playlist at a time, but nevermind

There is a playlist loader plugin for 1.6 now https://github.com/rithik-b/PlaylistLoaderPlugin supporting songs in multiple lists. I prefer this folder approach though.

**Comment by jeremys18** [comment]
Will fix this tonight. Thanks. :)

**Comment by jeremys18** [comment]
Fixed. Will now warn you and allow you to fix the file yourself or overwrite it with valid xml. According to xml standards, everything must be lowercased.
