### ISSUE TITLE
Why hashes are take form API?

### ISSUE THREAD

**Issue by nargatte** [jeremys18/BeatSaberPlaylistMover#4]
This is time consuming strategy especially when there are 500+ maps. We can use metadata.dat files witch contain the same information as API returns. I put 
`var json = File.ReadAllText(Path.Combine(folder.FullName, "metadata.dat"));` and commented API request in `GetSongFolderHashesAsync ` function and it has worked for me.

**Comment by jeremys18** [comment]
Will look into this. I'm not sure what that file is but will check it out tomorrow and implement the changes if it has whats needed.

**Comment by jeremys18** [comment]
That file only exists in certain cases. 99% of my downloaded songs do NOT have that file. I will update the code to use the file if it exists or use the api when it doesn't. That should save some time and bandwidth.
